name: TiraEat Deployment
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.1.0
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: /tiraeat/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: main # The branch the action should deploy to.
        build_folder: dist/tiraeat # The folder where your project is supposed to be after running ng build by the action.
    - name: Copy file
      # You may pin to the exact commit or the version.
      # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: dist/tiraeat/index.html
        # Target file
        target: ./404.html

